# PyTorch Tutorial - Part 1
> "Part 1 of the PyTorch tutorial -- I'm transitioning from TF to PyTorch and I'm starting from the complete basics here."

- toc: true
- branch: master
- badges: true
- comments: true
- author: Scott Wolf
- categories: [PyTorch, jupyter]

# Tensors!

As I transition from TensorFlow and Keras to PyTorch, I am going back through the basic docs of PyTorch and this series of posts will document that. Nearly all of this is directly from the PyTorch tutorials but rewriting and commenting will hopefully help me learn and possibly help others make the TF -> PyTorch transition cleaner!

Building tensors! Just like with most deep learning frameworks, PyTorch uses tensors to encode the inputs and outputs of models along with the model parameters. The main difference between the n-dimensional arrays of NumPy (ndarrays) is that they're compatible with hardware accelerators and optimized for automatic differentiation.

In [2]:
# Building tensors

import torch
import numpy as np

In [3]:
# Lets build directly from data!

data = [[1, 2], [3, 4]]
data_tensor = torch.tensor(data)

# This also works from numpy arrays!
data_np = np.array(data)
data_tensor_from_np = torch.from_numpy(data_np)

# Or even from another tensor!

ones_tensor = torch.ones_like(data_tensor)
print(f"Ones tensor: \n {ones_tensor} \n")

rand_tensor = torch.rand_like(data_tensor, dtype=torch.float)  # dtype required!
print(f"Random tensor: \n {rand_tensor} \n")

Ones tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random tensor: 
 tensor([[0.3120, 0.7831],
        [0.9336, 0.7780]]) 



In [4]:
# Or as above with just a shape!
shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.0923, 0.6174, 0.4717],
        [0.7022, 0.7585, 0.7783]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [5]:
print(f"Shape of tensor: {rand_tensor.shape}")
print(f"Datatype of tensor: {rand_tensor.dtype}")
print(f"Device tensor is stored on: {rand_tensor.device}")

Shape of tensor: torch.Size([2, 3])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Operations

Now lets quickly move into operations on tensors. Because we're working on Colab, we're gonna go ahead and move it to the GPU for speed!

In [9]:
# Make sure cuda is available and, if so, move the tensor.
if torch.cuda.is_available():
    print("Cuda is available -- moving the tensor to the GPU!")
    tensor = tensor.to("cuda")

Cuda is available -- moving the tensor to the GPU!


In [12]:
# Just like numpy!
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:, 1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [15]:
# We can concatenate them just like normal arrays
# Here we're just appending along dim 1 (cols)

print(torch.cat([tensor, tensor, tensor], dim=1))

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


Now onto some actual computations. Lets start with some basic operations.

In [18]:
# y1, y2, and y3 are equivalent.
# Note that for y3, we're just filling a preallocated tensor with the product.
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [19]:
# We can directly extend this to element-wise product as well
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [24]:
# Now some aggregate metrics -- note we can use .item() to get back to a python numerical.
sum = tensor.sum()
print(sum.item(), type(sum.item()))

12.0 <class 'float'>


In [27]:
# In-place operations!

print(f"{tensor} \n")
tensor.add_(5)  # Just leave off the _ to stop this from being in-place!
print(f"{tensor}")

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]) 

tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]])


## NumPy bridging!
We can share the underlying memory between tensors and numpy arrays when on the cpu.

In [30]:
t = torch.ones(5)
print(f"t: {t}")

n = t.numpy()
print(f"n: {n}")

t[2] = 123

print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
t: tensor([  1.,   1., 123.,   1.,   1.])
n: [  1.   1. 123.   1.   1.]


In [32]:
# from numpy does this too!

n = np.ones(5)
print(f"n: {n}")

t = torch.from_numpy(n)
print(f"t: {t}")


n[2] = 123

print(f"n: {n}")
print(f"t: {t}")

n: [1. 1. 1. 1. 1.]
t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
n: [  1.   1. 123.   1.   1.]
t: tensor([  1.,   1., 123.,   1.,   1.], dtype=torch.float64)
